---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-azure-rgs
  namespace: test-pods
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: k8s-admin
          restartPolicy: Never
          containers:
          - name: cleanup-azure-rgs
            image: ghcr.io/e2e-win/k8s-e2e-runner:master
            imagePullPolicy: Always
            command:
            - /workspace/cleanup-azure-rgs.py
            args:
            # Cleanup resource groups older than 6h.
            - --max-age-minutes=360
            env:
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_SUBSCRIPTION_ID
                  name: az-credentials
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_TENANT_ID
                  name: az-credentials
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_ID
                  name: az-credentials
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_SECRET
                  name: az-credentials
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-admin-role-binding
  namespace: test-pods
subjects:
- kind: ServiceAccount
  name: k8s-admin
  namespace: test-pods
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-admin
  namespace: test-pods
