---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-backup
  namespace: test-pods
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: kube-backup
            image: e2eteam/kube-backup:latest
            imagePullPolicy: Always
            env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_ID
                  name: prod-azcreds
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_SECRET
                  name: prod-azcreds
            - name: AZURE_SUB_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_SUB_ID
                  name: prod-azcreds
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_TENANT_ID
                  name: prod-azcreds
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT
                  name: prod-azcreds
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT_KEY
                  name: prod-azcreds
            - name: BACKUP_KEEP_DAYS
              value: "90"
            - name: BACKUP_CONFIGMAPS
              value: "default/config,default/plugins,default/job-config"
            - name: BACKUP_SECRETS
              value: "default/hmac-token,default/oauth-token,test-pods/azcreds,test-pods/prod-azcreds,test-pods/service-account,test-pods/ssh-key-default,test-pods/aks-azure-cred,test-pods/aks-azure-cred-upstream,test-pods/aks-azure-ssh,test-pods/aks-azure-storage,test-pods/aks-docker-pass,test-pods/aks-service-account,test-pods/aks-ssh-key-secret,test-pods/kubeconfig"
            - name: ENCRYPTION_KEY
              value: /etc/ssh/id_rsa.pub
            - name: AZURE_STORAGE_CONTAINER_PROW_BKP
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_CONTAINER_PROW_BKP
                  name: prod-azcreds
            volumeMounts:
            - name: kubeconfig
              mountPath: /root/.kube
              readOnly: true
            - name: ssh
              mountPath: /etc/ssh
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: kubeconfig
            secret:
              defaultMode: 0400
              secretName: kubeconfig
          - name: ssh
            secret:
              defaultMode: 0400
              secretName: ssh-key-default
