---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prow-backup
  namespace: test-pods
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: k8s-admin
          restartPolicy: Never
          containers:
          - name: prow-backup
            image: ghcr.io/e2e-win/prow-backup:main
            imagePullPolicy: Always
            env:
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_SUBSCRIPTION_ID
                  name: az-credentials
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_TENANT_ID
                  name: az-credentials
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_ID
                  name: az-credentials
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_SECRET
                  name: az-credentials
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT
                  name: az-credentials
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT_KEY
                  name: az-credentials
            - name: AZURE_STORAGE_CONTAINER_PROW_BKP
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_CONTAINER_PROW_BKP
                  name: az-credentials
            - name: BACKUP_KEEP_DAYS
              value: "90"
            - name: BACKUP_CONFIGMAPS
              value: "prow/config,prow/plugins,prow/job-config"
            - name: BACKUP_SECRETS
              value: "prow/hmac-token,prow/github-token,test-pods/github-readonly-token,test-pods/az-credentials,test-pods/gcs-credentials,test-pods/ssh-key,test-pods/windows-private-registry-docker-config"
            - name: ENCRYPTION_KEY
              value: /etc/ssh/id_rsa.pub
            volumeMounts:
            - name: ssh
              mountPath: /etc/ssh
              readOnly: true
          volumes:
          - name: ssh
            secret:
              defaultMode: 0400
              secretName: ssh-key
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-admin-role-binding
  namespace: test-pods
subjects:
- kind: ServiceAccount
  name: k8s-admin
  namespace: test-pods
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-admin
  namespace: test-pods
