images:
  infrastructure-azure:
    repository: e2eteam
    tag: v0.4.6-windows
  bootstrap-kubeadm:
    repository: e2eteam
    tag: v0.3.8
  control-plane-kubeadm:
    repository: e2eteam
    tag: v0.3.8
  cert-manager:
    repository: e2eteam
    tag: v0.11.0
  cluster-api:
    repository: e2eteam
    tag: v0.3.8
