plank:
  default_decoration_configs:
    "*":
      timeout: 6h
      grace_period: 15m
      gcs_configuration:
        bucket: k8s-ovn
        path_strategy: explicit
        default_org: kubernetes
        default_repo: kubernetes
      gcs_credentials_secret: gcs-credentials
      skip_cloning: true
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20230329-c93d79fb7d
        entrypoint: gcr.io/k8s-prow/entrypoint:v20230329-c93d79fb7d
        initupload: gcr.io/k8s-prow/initupload:v20230329-c93d79fb7d
        sidecar: gcr.io/k8s-prow/sidecar:v20230329-c93d79fb7d

sinker:
  max_prowjob_age: 72h
  max_pod_age: 72h

prowjob_namespace: prow
pod_namespace: test-pods
decorate_all_jobs: true

presets:
- labels:
    preset-prod-azure-account: "true"
  env:
  - name: AZURE_SUBSCRIPTION_ID
    valueFrom:
      secretKeyRef:
        key: AZURE_SUBSCRIPTION_ID
        name: az-credentials
  - name: AZURE_TENANT_ID
    valueFrom:
      secretKeyRef:
        key: AZURE_TENANT_ID
        name: az-credentials
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        key: AZURE_CLIENT_ID
        name: az-credentials
  - name: AZURE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: AZURE_CLIENT_SECRET
        name: az-credentials

- labels:
    preset-ssh-key: "true"
  env:
  - name: SSH_PRIVATE_KEY_PATH
    value: /etc/ssh/id_rsa
  - name: SSH_PUBLIC_KEY_PATH
    value: /etc/ssh/id_rsa.pub
  volumes:
  - name: ssh
    secret:
      defaultMode: 0400
      secretName: ssh-key
  volumeMounts:
  - name: ssh
    mountPath: /etc/ssh
    readOnly: true

- labels:
    preset-windows-private-registry-cred: "true"
  env:
  - name: DOCKER_CONFIG_FILE
    value: /etc/docker-cred/config.json
  volumes:
  - name: windows-private-registry-cred
    secret:
      secretName: windows-private-registry-docker-config
  volumeMounts:
  - name: windows-private-registry-cred
    mountPath: /etc/docker-cred/
    readOnly: true

- labels:
    preset-github-readonly-token: "true"
  env:
  - name: GITHUB_TOKEN
    valueFrom:
      secretKeyRef:
        key: GITHUB_TOKEN
        name: github-readonly-token

- labels:
    preset-test-regex: "true"
  env:
  - name: TEST_FOCUS_REGEX
    value: \\[Conformance\\]|\\[NodeConformance\\]|\\[sig-windows\\]|\\[sig-apps\\].CronJob|\\[sig-api-machinery\\].ResourceQuota|\\[sig-scheduling\\].SchedulerPreemption
  - name: TEST_SKIP_REGEX
    value: \\[LinuxOnly\\]|\\[Serial\\]|\\[alpha\\]|GMSA|\\[Feature\\:GPUDevicePlugin\\]|\\[sig-api-machinery\\].Garbage.collector
