name: Kube-Proxy Windows HPC Image

on:
  push:
    branches:
      - main

jobs:
  buildx-kube-proxy-windows-hpc:
    uses: ./.github/workflows/docker-buildx.yaml
    with:
      image_name: kube-proxy-windows-hpc
      context: ./e2e-runner/e2e_runner/ci/capz_flannel/kube-proxy/kube-proxy-windows-hpc
      platform: windows/amd64
    secrets: inherit
