name: Prow Backup

on:
  push:
    branches:
      - main

jobs:
  buildx-prow-backup:
    uses: ./.github/workflows/docker-buildx.yaml
    with:
      image_name: prow-backup
      context: ./prow/backup
      platform: linux/amd64
    secrets: inherit
